version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '{asctime} - {name} - {levelname} {message}'
    style: '{'
  verbose:
    format: '{asctime} - {name} - {levelname} - {module} - {process} - {thread} - {message}'
    style: '{'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: "logs/logfile.log"
loggers:
  defaultLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
